Dev
misterbyf/MindKdev pull request #1
Opened 2021-01-11 03:29 UTC by misterbyf

Вот обращение к базе через кнекс, ещё смотрел на модуль express-di, тоже можно использовать, просто через кнекс удобно обращаться к базе. При установке postgres были некоторые ошибки, в частности служба базы автоматически прекращала работу(проблема винды), хорошо что у меня был дата грид и я адекватно смог взаимодействовать с базой. Так же переделал роутер в более стандартный вид.

2021-01-11 19:59 UTC, ddavidov requested changes
Только одно важное замечание - то, которое про конфиги. Остальное - так... рекомендашки. И можно сливать в main

2021-01-11 19:59 UTC, ddavidov commented on api/config/develop.config.js
> +      password : "password",
Сюда заводим переменные из конфига. Или как process.env или через класс конфига. Логинов паролей и хостов тут хардкодом делеть не стоит. Даже если они от localhost'a

2021-01-11 19:59 UTC, ddavidov commented on api/controllers/user.controller.js
> +        db.select("*").from("person").then((data) => {
Подскажу такую штуку. Но это необязательно делать. Просто если название таблицы вынести в константу. Даже как внутриклассовую. Типа `const tableName = 'person'`. То в случае изменения названия таблицы можно будет только константе значение новое задать 1 раз. Но это только рекомендация.

2021-01-11 19:59 UTC, ddavidov commented on api/package.json
> +    "mongoose": "^5.11.8",
Серьёзная заявка) А зачем и то и то? (просто вопрос)

2021-01-11 19:59 UTC, ddavidov commented on front/.eslintcache
> +[{"D:\\NodeJSFile\\MindKTask\\front\\src\\index.js":"1","D:\\NodeJSFile\\MindKTask\\front\\src\\reportWebVitals.js":"2","D:\\NodeJSFile\\MindKTask\\front\\src\\App.js":"3"},{"size":500,"mtime":499162
Тоже не нужен, лучше заигнорить.

2021-01-12 12:17 UTC, misterbyf commented on api/config/develop.config.js
> +      password : "password",
Вообще, сначало было так, но у меня просто приложение не работало, я занёс все переменные в конфиг и вызывал через функция get, данные просто не передавались

2021-01-12 12:19 UTC, misterbyf commented on api/package.json
> +    "mongoose": "^5.11.8",
У меня какой-то сбой был в версиях, исправлял

2021-01-12 12:19 UTC, misterbyf commented on api/config/develop.config.js
> +      password : "password",
То ли с зависимостями какая-то проблема.

2021-01-12 12:20 UTC, misterbyf commented on api/controllers/user.controller.js
> +        db.select("*").from("person").then((data) => {
Ну в дальнейшем я так и буду делать

2021-01-21 09:39 UTC, ddavidov requested changes
И лучше разделять PR. Фронт отдально, апи - отдельно.

2021-01-21 09:39 UTC, ddavidov commented on .idea/.gitignore
> +# Default ignored files
шось не то. Игнорим эти файлы и выбрасываем из индекса.

2021-01-21 09:39 UTC, ddavidov commented on api/middleware/passport.js
> +                const user = await User.findByEmail(payload.email);
Если jwt, то это вот можно не делать.

2021-01-21 09:39 UTC, ddavidov commented on api/package.json
> +    "mongoose": "^5.11.8",
Я про то, что и pg и mongo используется. То задумка есть в том или...?

2021-01-21 09:39 UTC, ddavidov commented on front/.eslintcache
> +[{"D:\\NodeJSFile\\MindKTask\\front\\src\\index.js":"1","D:\\NodeJSFile\\MindKTask\\front\\src\\reportWebVitals.js":"2","D:\\NodeJSFile\\MindKTask\\front\\src\\App.js":"3","D:\\NodeJSFile\\MindKTask\
не, это тоже игнорим

2021-01-21 09:59 UTC, misterbyf commented on api/middleware/passport.js
> +                const user = await User.findByEmail(payload.email);
Что именно можно не делать?

2021-01-21 10:00 UTC, misterbyf commented on front/.eslintcache
> +[{"D:\\NodeJSFile\\MindKTask\\front\\src\\index.js":"1","D:\\NodeJSFile\\MindKTask\\front\\src\\reportWebVitals.js":"2","D:\\NodeJSFile\\MindKTask\\front\\src\\App.js":"3","D:\\NodeJSFile\\MindKTask\
Там по поводу монго я почищу, начальные задание я на монго делал просто, а у нас здесь курс связан с постгре

2021-02-05 23:41 UTC, merged